
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CEROUNA = 19;
  public static final int GUION = 8;
  public static final int CADENA = 21;
  public static final int CONCATENACION = 16;
  public static final int DOSPUNTOS = 6;
  public static final int UNOMAS = 20;
  public static final int DECIMAL = 22;
  public static final int CESPECIAL = 13;
  public static final int ALFABETO = 11;
  public static final int LLIZQ = 2;
  public static final int COMA = 10;
  public static final int MAYORQ = 9;
  public static final int LLDER = 3;
  public static final int COMILLASDOBLES = 12;
  public static final int EOF = 0;
  public static final int FINSECCION = 5;
  public static final int COMILLA = 23;
  public static final int DISYUNCION = 17;
  public static final int ESP = 24;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 7;
  public static final int CEROMAS = 18;
  public static final int RANGO = 14;
  public static final int RESERVADA = 4;
  public static final int PTCOMA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLIZQ",
  "LLDER",
  "RESERVADA",
  "FINSECCION",
  "DOSPUNTOS",
  "IDENTIFICADOR",
  "GUION",
  "MAYORQ",
  "COMA",
  "ALFABETO",
  "COMILLASDOBLES",
  "CESPECIAL",
  "RANGO",
  "PTCOMA",
  "CONCATENACION",
  "DISYUNCION",
  "CEROMAS",
  "CEROUNA",
  "UNOMAS",
  "CADENA",
  "DECIMAL",
  "COMILLA",
  "ESP"
  };
}

